### ISSUE TITLE
Where is the Download

### ISSUE THREAD

**Issue by katzendrama** [MCProHosting/DynamicBungee#1]
On the Spigot Website you can also find this Plugin but the Dropbox Link is broken.....
Can you please send me DynamicBungee and DynamicBukkit........

Thanks 
BrummBrumm03

**Comment by MattJustMatt** [comment]
Hi Brumm, this is a very old project and its maintainers are no longer with us. You would need to compile it manually.

**Comment by katzendrama** [comment]
Okay Thanks

2015-10-03 17:37 GMT+02:00 Matthew Salsamendi notifications@github.com:
